package com.livebox.common.entity;

import jakarta.persistence.Column;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.experimental.SuperBuilder;
import org.springframework.data.annotation.CreatedBy;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedBy;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.Instant;
import java.util.UUID;

/**
 * BaseEntity — abstract base class cho tất cả JPA Entities trong LiveBox.
 *
 * <p><b>Quy tắc áp dụng (coding_conventions.md §4):</b>
 * <ul>
 *   <li>Cấm {@code @Data} — tránh {@code StackOverflowError} do {@code toString()} /
 *       {@code hashCode()} đệ quy khi entities có quan hệ {@code OneToMany} / {@code ManyToOne}.</li>
 *   <li>Dùng {@code @Getter} {@code @Setter} riêng lẻ thay thế.</li>
 *   <li>Audit fields ({@code createdAt}, {@code updatedAt}, {@code createdBy}, {@code updatedBy})
 *       tự động populate bởi Spring Data JPA Auditing — kích hoạt qua
 *       {@code @EnableJpaAuditing} trong {@link com.livebox.config.AppConfig}.</li>
 * </ul>
 *
 * <p><b>Primary Key strategy:</b> {@code GenerationType.UUID} — Hibernate 6 tự generate
 * UUID v4 trước khi INSERT, không phụ thuộc vào DB sequence. Phù hợp với PostgreSQL
 * (kiểu {@code uuid}) và đảm bảo tính duy nhất toàn cục.
 *
 * <p><b>Soft Delete:</b> {@code isDeleted} + {@code deletedAt} cho phép "xóa mềm" — record
 * vẫn tồn tại trong DB để bảo toàn lịch sử (chat history, audit log). Repository layer
 * có trách nhiệm filter {@code WHERE is_deleted = false} trong các query nghiệp vụ.
 */
@Getter
@Setter
@NoArgsConstructor
@MappedSuperclass
@SuperBuilder
@EntityListeners(AuditingEntityListener.class)
public abstract class BaseEntity {

    // ─────────────────────────────────────────────────────────────────────────
    // Primary Key
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * UUID primary key — generated by Hibernate before INSERT (no DB round-trip).
     * Maps to PostgreSQL {@code uuid} column type.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "id", updatable = false, nullable = false)
    private UUID id;

    // ─────────────────────────────────────────────────────────────────────────
    // Audit — Timestamps
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Thời điểm record được tạo (UTC). Set tự động bởi {@link AuditingEntityListener}.
     * {@code updatable = false} đảm bảo giá trị không bao giờ bị ghi đè.
     */
    @CreatedDate
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /**
     * Thời điểm record được cập nhật lần cuối (UTC). Set tự động bởi {@link AuditingEntityListener}.
     */
    @LastModifiedDate
    @Column(name = "updated_at", nullable = false)
    private Instant updatedAt;

    // ─────────────────────────────────────────────────────────────────────────
    // Audit — Actor (Who)
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Username / email của người tạo record. Populate tự động từ
     * {@code SecurityContextHolder} thông qua {@code AuditorAware} bean
     * (sẽ implement ở Sprint 1 Auth module).
     */
    @CreatedBy
    @Column(name = "created_by", updatable = false, length = 100)
    private String createdBy;

    /**
     * Username / email của người cập nhật record lần cuối.
     */
    @LastModifiedBy
    @Column(name = "updated_by", length = 100)
    private String updatedBy;

    // ─────────────────────────────────────────────────────────────────────────
    // Soft Delete
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Cờ soft delete. {@code true} = record đã bị xóa mềm, KHÔNG hiển thị
     * trong các query nghiệp vụ thông thường.
     *
     * <p>Default {@code false} — record mới luôn ở trạng thái active.
     */
    @Builder.Default
    @Column(name = "is_deleted", nullable = false)
    private boolean isDeleted = false;

    /**
     * Thời điểm record bị xóa mềm (UTC). {@code null} khi record còn active.
     * Được set thủ công trong Service layer khi thực hiện soft delete.
     */
    @Column(name = "deleted_at")
    private Instant deletedAt;

    // ─────────────────────────────────────────────────────────────────────────
    // Soft Delete Helper
    // ─────────────────────────────────────────────────────────────────────────

    /**
     * Thực hiện soft delete: đánh dấu {@code isDeleted = true} và ghi nhận
     * thời điểm xóa. Gọi method này trong Service layer thay vì gọi
     * {@code repository.delete(entity)}.
     *
     * <p>Ví dụ:
     * <pre>
     *   serverMember.softDelete();
     *   memberRepository.save(serverMember);
     * </pre>
     */
    public void softDelete() {
        this.isDeleted = true;
        this.deletedAt = Instant.now();
    }
}
