/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#005762",
        "on-secondary-container": "#e4daff",
        "background": "#0b0e14",
        "secondary-fixed": "#d8caff",
        "secondary-dim": "#7e51ff",
        "on-surface": "#ecedf6",
        "on-tertiary-container": "#001d3f",
        "error-container": "#9f0519",
        "surface-container-lowest": "#000000",
        "surface-container-low": "#10131a",
        "error": "#ff716c",
        "primary-fixed": "#00e3fd",
        "on-background": "#ecedf6",
        "on-primary-fixed": "#003840",
        "on-error-container": "#ffa8a3",
        "secondary-container": "#591adc",
        "on-primary-container": "#004d57",
        "primary": "#81ecff",
        "surface-container-highest": "#22262f",
        "surface-variant": "#22262f",
        "surface-dim": "#0b0e14",
        "on-tertiary": "#002a55",
        "primary-dim": "#00d4ec",
        "surface-bright": "#282c36",
        "on-secondary-fixed": "#3b00a0",
        "inverse-on-surface": "#52555c",
        "on-tertiary-fixed-variant": "#003971",
        "on-surface-variant": "#a9abb3",
        "inverse-surface": "#f9f9ff",
        "tertiary-dim": "#5c9ffc",
        "primary-container": "#00e3fd",
        "inverse-primary": "#006976",
        "primary-fixed-dim": "#00d4ec",
        "secondary-fixed-dim": "#cabaff",
        "on-error": "#490006",
        "surface-container-high": "#1c2028",
        "tertiary": "#70aaff",
        "outline": "#73757d",
        "tertiary-container": "#599cf9",
        "on-primary": "#005762",
        "error-dim": "#d7383b",
        "surface-container": "#161a21",
        "secondary": "#a68cff",
        "on-secondary": "#25006b",
        "tertiary-fixed-dim": "#65a4ff",
        "tertiary-fixed": "#80b2ff",
        "surface-tint": "#81ecff",
        "outline-variant": "#45484f",
        "on-secondary-fixed-variant": "#591bdc",
        "on-tertiary-fixed": "#001835",
        "surface": "#0b0e14"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"]
      }
    },
  },
  plugins: [],
}
